server:
  port: 9093

spring:
  application:
    name: USER-AUTH-SERVICE
  zipkin:
      base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
#  cloud:
#    gateway:
#      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/**
#        - id: FLIGHT-SERVICE
#          uri: lb://FLIGHT-SERVICE
#          predicates:
#            - Path=/flight/**
#        - id: AIRPORT-SERVICE
#          uri: lb://AIRPORT-SERVICE
#          predicates:
#            - Path=/airport/**
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
  datasource:
      #url: jdbc:mysql://flightdb.cttbplnts240.us-east-1.rds.amazonaws.com:3306/flight_booking
      url: jdbc:mysql://localhost:3306/flight_booking
      username: root
      #password: Password123
      password: Password@123
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      properties:
           hibernate:
              format_sql: true
              dialect: org.hibernate.dialect.MySQL57InnoDBDialect

sprint2:
  app:
   jwtSecret: sprint2SecretKey
   jwtExpirationMs: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always